import LoginBtn from "@/components/LoginBtn";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
// import AuthSession from "./AuthSession";
import QueryProvider from "./QueryProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let res = cookies().get("쿠키이름");
  console.log(res);
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <div className="navbar">
            <Link href="/" className="logo">
              JoyForum
            </Link>
            <Link href="/list">List</Link>
            <LoginBtn />
          </div>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
